Better diagnostics around common failure scenarios (git command not found, no git repo, and no .gitconfig configured).

diff --git a/git-tag-version b/git-tag-version
--- a/git-tag-version
+++ b/git-tag-version
@@ -1,17 +1,20 @@
 #!/usr/bin/env sh
 set -e
 
-this="$(basename ${0})"
-calculate="$(dirname "${0}")/calculate-version"
-describe="$(git describe --tags 2>/dev/null || echo "0.0.0")"
-version=""
-
 case "${1}" in
-  major) version="$("${calculate}" -M "${describe}")"  ;;
-  minor) version="$("${calculate}" -m "${describe}")"  ;;
-  patch) version="$("${calculate}" -p "${describe}")"  ;;
-  *) echo "usage: ${this} [major|minor|patch]" && exit 1
+  M|m|p) ;;
+  *) echo "usage: $(basename ${0}) [M|m|p]" && exit 1
 esac
 
-git tag -a "${version}" -m "" 2>/dev/null || \
-  (echo "Unable to tag repository with version '${version}'." && exit 1)
+message="Git command not found. Git executable is required to tag git repositories."
+command -v git >/dev/null 2>/dev/null || (echo "${message}" && exit 2)
+
+message="Git repository not found. This command must be run within a git repository."
+git rev-parse --git-dir >/dev/null 2>/dev/null || (echo "${message}" && exit 3)
+
+calculate="$(dirname "${0}")/calculate-version"
+describe="$(git describe --tags 2>/dev/null || echo "0.0.0")"
+version="$("${calculate}" -${1} "${describe}")" # this could fail
+
+message="Unable to tag repository with version '${version}'. Does your user environment have your .gitconfig set with user.name and user.email?"
+git tag -a "${version}" -m "" 2>/dev/null || (echo "${message}" && exit 4)
