Revising error messages; additional error checks to test if tag already exists.

diff --git a/git-tag-version b/git-tag-version
--- a/git-tag-version
+++ b/git-tag-version
@@ -14,17 +14,20 @@ git rev-parse --git-dir >/dev/null 2>/dev/null || (echo "${message}" && exit 3)
 
 calculate="$(dirname "${0}")/calculate-version"
 describe="$(git describe --tags 2>/dev/null || echo "0.0.0")"
-dirty=$(echo "${2}" | awk '{split($0,a,"-"); print a[2]}')
+dirty=$(echo "${describe}" | awk '{split($0,a,"-"); print a[2]}')
 
-message="No changes"
+message="Repository already tagged with '${describe}'."
 if test "v${version}" != "v0.0.0" && test "x${dirty}" = "x"; then
 	echo "${message}"
 	exit 0
 fi
 
-version="$("${calculate}" -${1} "${describe}")" # this could fail
+version="$("${calculate}" -${1} "${describe}")" # TODO: this could fail if ${describe} is malformed
 
-message="Unable to tag repository with version '${version}'. Does the tag alread exist or does your user environment have your .gitconfig set with user.name and user.email?"
-git tag -a "${version}" -m "" 2>/dev/null || (echo "${message}" && exit 4)
+message="Unable to tag the repository with version '${version}'. The tag already exists."
+git-rev-parse "${version}" >/dev/null 2>/dev/null && true || (echo "${message}" && exit 4)
+
+message="Unable to tag repository with version '${version}'. Does your user environment have your .gitconfig set with user.name and user.email?"
+git tag -a "${version}" -m "" 2>/dev/null || (echo "${message}" && exit 5)
 
 echo "Tagged repository with version '${version}'."
